# EIJC Pandas Workshop 2018

In [72]:
import pandas as pd
pd.options.display.float_format = '{:,.2f}'.format

In [87]:
df = pd.read_csv("United Kingdom_all_data-filtered.csv")

There is GB and UK codes in the data. Make sure that we replace GB with UK in order to analyse only one country, the UK.

In [74]:
df['buyer_country'] = df['buyer_country'].str.replace('GB', 'UK')
df['buyer_country'].value_counts()

UK    267425
IE        30
DE        19
FR        13
ES         8
PL         4
GI         3
IT         3
PT         1
BG         1
FI         1
BE         1
Name: buyer_country, dtype: int64

In [75]:
df['buyer_city_clean'] = df['buyer_city'].str.lower()

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 296862 entries, 0 to 296861
Data columns (total 34 columns):
Unnamed: 0                                                296862 non-null int64
tender_id                                                 296862 non-null object
tender_country                                            296862 non-null object
tender_year                                               274825 non-null float64
tender_title                                              296644 non-null object
tender_mainCpv                                            248947 non-null float64
tender_cpvs                                               296724 non-null object
tender_procedureType                                      289181 non-null object
buyer_id                                                  296862 non-null object
buyer_name                                                272518 non-null object
buyer_city                                                271791 non-null object
buyer_country                                             267509 non-null object
buyer_postcode                                            269833 non-null object
bidder_id                                                 292569 non-null object
bidder_name                                               292424 non-null object
bidder_city                                               209290 non-null object
bidder_country                                            202831 non-null object
bidder_postcode                                           216348 non-null object
bid_price                                                 53408 non-null float64
bid_price_EUR                                             53408 non-null float64
bid_price_currency                                        101177 non-null object
tender_estimatedPrice                                     28171 non-null float64
tender_estimatedPrice_EUR                                 28171 non-null float64
tender_estimatedPrice_currency                            41469 non-null object
tender_finalPrice                                         120654 non-null float64
tender_finalPrice_EUR                                     120654 non-null float64
tender_finalPrice_currency                                120654 non-null object
tender_indicator_INTEGRITY_ADVERTISEMENT_PERIOD           219429 non-null float64
tender_indicator_INTEGRITY_CALL_FOR_TENDER_PUBLICATION    219688 non-null float64
tender_indicator_INTEGRITY_DECISION_PERIOD                209516 non-null float64
tender_indicator_INTEGRITY_NEW_COMPANY                    13474 non-null float64
tender_indicator_INTEGRITY_PROCEDURE_TYPE                 219688 non-null float64
tender_indicator_INTEGRITY_SINGLE_BID                     197172 non-null float64
tender_indicator_INTEGRITY_TAX_HAVEN                      208662 non-null float64
dtypes: float64(15), int64(1), object(18)
memory usage: 77.0+ MB

## Read in CPV codes

In [88]:
cpv = pd.read_csv('CPVs.csv')
cpv.head()

,Unnamed: 0,REAL_CODE,PLAIN_CODE,NAME
0,2,3.00,3000000,"Agricultural, farming, fishing, forestry and r..."
1,3,31.00,3100000,Agricultural and horticultural products
2,4,311.00,3110000,"Crops, products of market gardening and hortic..."
3,5,"3,111.00",3111000,Seeds
4,6,"31,111.00",3111100,Soya beans

In [90]:
cpv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9454 entries, 0 to 9453
Data columns (total 4 columns):
Unnamed: 0    9454 non-null int64
REAL_CODE     9448 non-null float64
PLAIN_CODE    9454 non-null int64
NAME          9454 non-null object
dtypes: float64(1), int64(2), object(1)
memory usage: 295.5+ KB

In [93]:
len(df)

296862

In [100]:
len(df_cpv)

296862

In [99]:
df_cpv = pd.merge(df, cpv, left_on="tender_mainCpv", right_on="PLAIN_CODE", how="left")
df_cpv.head()

,Unnamed: 0_x,tender_id,tender_country,tender_year,tender_title,tender_mainCpv,tender_cpvs,tender_procedureType,buyer_id,buyer_name,...,tender_indicator_INTEGRITY_CALL_FOR_TENDER_PUBLICATION,tender_indicator_INTEGRITY_DECISION_PERIOD,tender_indicator_INTEGRITY_NEW_COMPANY,tender_indicator_INTEGRITY_PROCEDURE_TYPE,tender_indicator_INTEGRITY_SINGLE_BID,tender_indicator_INTEGRITY_TAX_HAVEN,Unnamed: 0_y,REAL_CODE,PLAIN_CODE,NAME
0,3,0d7b8078-b007-48ae-aa7d-6c2a52056108,UK,nan,Older People — Creigiau and St Fagans.,"85,312,000.00",85312000,OPEN,EU_body_81cdafe504d6cc4a1ba541281e6c17178db683...,Cardiff City Council,...,0.00,100.00,100.00,100.00,100.00,100.00,5.00,"85,312.00","85,312,000.00",Social work services without accommodation
1,63,09f1310f-8612-4313-8792-d003ad91b1f0,UK,nan,Mini-cabs and Taxis Saloons.,"60,000,000.00",60000000,OPEN,EU_body_c04712a23e83f993d38e793f12641216f9ae04...,London Borough of Haringey,...,0.00,100.00,100.00,100.00,100.00,100.00,0.00,nan,"60,000,000.00",Transport services (excl. Waste transport)
2,64,09f58d40-0790-4456-843e-dff2de5a2c77,UK,nan,4503 - AV installation - 32 teaching rooms,"32,322,000.00",32322000,RESTRICTED,EU_body_2ed4c44bc08e032ca54a8d626740fccf081f30...,University of Portsmouth,...,0.00,100.00,nan,100.00,100.00,100.00,5.00,"32,322.00","32,322,000.00",Multimedia equipment
3,79,0e3caf26-6731-4a6b-84c6-046ff5528e98,UK,nan,Library resources.,"22,113,000.00","22113000,22200000,48161000",OPEN,EU_body_dd617693ccd2769369e8d5de79480636f119b4...,Crescent Purchasing Consortium,...,100.00,nan,nan,100.00,nan,nan,5.00,"22,113.00","22,113,000.00",Library books
4,80,0e3caf26-6731-4a6b-84c6-046ff5528e98,UK,nan,Library resources.,"22,113,000.00","22113000,22200000,48161000",OPEN,EU_body_dd617693ccd2769369e8d5de79480636f119b4...,Crescent Purchasing Consortium,...,100.00,nan,nan,100.00,nan,nan,5.00,"22,113.00","22,113,000.00",Library books

In [109]:
df_cpv[df_cpv["NAME"].str.contains("hat").fillna(False)]

,Unnamed: 0_x,tender_id,tender_country,tender_year,tender_title,tender_mainCpv,tender_cpvs,tender_procedureType,buyer_id,buyer_name,...,tender_indicator_INTEGRITY_CALL_FOR_TENDER_PUBLICATION,tender_indicator_INTEGRITY_DECISION_PERIOD,tender_indicator_INTEGRITY_NEW_COMPANY,tender_indicator_INTEGRITY_PROCEDURE_TYPE,tender_indicator_INTEGRITY_SINGLE_BID,tender_indicator_INTEGRITY_TAX_HAVEN,Unnamed: 0_y,REAL_CODE,PLAIN_CODE,NAME
10546,102281,6faccf6c-6563-4033-9b9b-0329c163e9f9,UK,nan,"F026-11 Supply of Ferric Sulphate 12,5 %.","24,313,122.00",24313122,NEGOTIATED_WITHOUT_PUBLICATION,EU_body_0514a27a761121c0a5c2b60c00807f7e1f09b3...,Southern Water,...,0.00,100.00,100.00,0.00,nan,nan,8.00,"24,313,122.00","24,313,122.00",Ferric sulphate
244991,22135,b5eb8503-02b2-4985-aaa1-8262e57607cd,UK,"2,011.00",Aluminium & Ferric Sulphate.,"24,313,122.00","24313122,24313123",NEGOTIATED_WITH_PUBLICATION,EU_body_9e361d1588c4a79456f90ca073f893e7be6ee8...,South West Water Ltd,...,0.00,100.00,nan,0.00,nan,100.00,8.00,"24,313,122.00","24,313,122.00",Ferric sulphate
255099,32597,3f6cea06-dc17-4cff-a718-bc73dd2ee236,UK,"2,011.00",The Supply of Iron Based Coagulants.,"24,313,122.00","24313122,24312122",NEGOTIATED_WITH_PUBLICATION,EU_body_47f88d6e1d8070af8bb85d9a6260aa4e9434ea...,Wessex Water Services Ltd,...,0.00,100.00,nan,0.00,100.00,100.00,8.00,"24,313,122.00","24,313,122.00",Ferric sulphate
255100,32598,3f6cea06-dc17-4cff-a718-bc73dd2ee236,UK,"2,011.00",The Supply of Iron Based Coagulants.,"24,313,122.00","24313122,24312122",NEGOTIATED_WITH_PUBLICATION,EU_body_47f88d6e1d8070af8bb85d9a6260aa4e9434ea...,Wessex Water Services Ltd,...,0.00,100.00,nan,0.00,100.00,100.00,8.00,"24,313,122.00","24,313,122.00",Ferric sulphate
255101,32599,3f6cea06-dc17-4cff-a718-bc73dd2ee236,UK,"2,011.00",The Supply of Iron Based Coagulants.,"24,313,122.00","24313122,24312122",NEGOTIATED_WITH_PUBLICATION,EU_body_47f88d6e1d8070af8bb85d9a6260aa4e9434ea...,Wessex Water Services Ltd,...,0.00,100.00,nan,0.00,100.00,100.00,8.00,"24,313,122.00","24,313,122.00",Ferric sulphate
263441,2139,2a35d888-6707-4b82-83eb-d59454cdfc9e,UK,"2,013.00",National Framework Agreement for the supply of...,"24,313,126.00","24313126,33696200",OPEN,EU_body_7c59a7ed12e64f0a57237de5407418cec89457...,NHS Blood & Transplant,...,0.00,100.00,nan,100.00,0.00,100.00,8.00,"24,313,126.00","24,313,126.00",Copper sulphate
275446,15084,daa03e2d-b0a2-415c-b64e-aa22fe2ee2e5,UK,"2,013.00",1126 supply of iron and aluminium salts and po...,"24,313,122.00","24313122,24312122,24313123,24312123",NEGOTIATED,EU_body_1be7e7544bb09361c763abe27fe758a8927134...,Thames Water Utilities Limited,...,100.00,0.00,nan,100.00,100.00,100.00,8.00,"24,313,122.00","24,313,122.00",Ferric sulphate
275447,15085,daa03e2d-b0a2-415c-b64e-aa22fe2ee2e5,UK,"2,013.00",1126 supply of iron and aluminium salts and po...,"24,313,122.00","24313122,24312122,24313123,24312123",NEGOTIATED,EU_body_1be7e7544bb09361c763abe27fe758a8927134...,Thames Water Utilities Limited,...,100.00,0.00,nan,100.00,100.00,100.00,8.00,"24,313,122.00","24,313,122.00",Ferric sulphate
275448,15086,daa03e2d-b0a2-415c-b64e-aa22fe2ee2e5,UK,"2,013.00",1126 supply of iron and aluminium salts and po...,"24,313,122.00","24313122,24312122,24313123,24312123",NEGOTIATED,EU_body_1be7e7544bb09361c763abe27fe758a8927134...,Thames Water Utilities Limited,...,100.00,0.00,nan,100.00,100.00,100.00,8.00,"24,313,122.00","24,313,122.00",Ferric sulphate

In [76]:
cols = ['buyer_city_clean', 'bidder_name',
        'tender_procedureType', 'tender_finalPrice_EUR']
df[cols]

,buyer_city_clean,bidder_name,tender_procedureType,tender_finalPrice_EUR
0,cardiff,Steddy Limited,OPEN,nan
1,london,Sam's Cars Limited,OPEN,nan
2,portsmouth,Pro AV,RESTRICTED,"155,478.00"
3,salford,"Askews and Holts Library Services Ltd, AT Litt...",OPEN,nan
4,salford,No bids were received for this lot so no award...,OPEN,nan
5,salford,"EBSCO Information Services, Prenax Ltd",OPEN,nan
6,salford,AT Little & Sons t/a Browns Books for Students...,OPEN,nan
7,london,Daryel Care,OPEN,nan
8,rugeley,Oaklands Nursing Home,OPEN,nan
9,preston,CENTRAL LANCASHIRE AGE CONCERN,RESTRICTED,nan
10,newport,Isle of Wight Council Internal Services,OPEN,nan
11,ipswich,The Consultancy Home Counties Ltd (TCHC),OPEN,nan
12,london,Mitie Security Servcies,RESTRICTED,nan
13,london,Airport Transfer Cars Ltd,OPEN,nan
14,rugeley,Beechfields Nursing Home Limited,OPEN,nan
15,rugeley,Hyde Lea Nursing Homes Ltd,OPEN,nan
16,london,Hills Consortium Limited,OPEN,nan
17,rugeley,St Quentin Senior Living,OPEN,nan
18,cardiff,Comfortcare partnership,OPEN,nan
19,birmingham,Passion 4 Care,OPEN,nan
20,birmingham,Bondcare Limited,OPEN,nan
21,birmingham,Servoca Plc,OPEN,nan
22,london,Metro Property Management Ltd,OPEN,nan
23,rugeley,Needwood House,OPEN,nan
24,cardiff,Evoo Healthcare,OPEN,nan
25,rugeley,Hawksyard Priory Nursing Home Limited,OPEN,nan
26,newport,Better at Home IOW Ltd,OPEN,nan
27,southend-on-sea,Brooklands Care Home Ltd,OPEN,nan
28,cardiff,Heritage Healthcare — Cardiff,OPEN,nan
29,birmingham,At Home With You,OPEN,nan
...,...,...,...,...
296832,belfast,RSA Northern Ireland Insurance Limited,RESTRICTED,"1,084,451.00"
296833,york,Bond Bryan Architects Ltd,OPEN,"371,503.00"
296834,newcastle upon tyne,Creative Space Management,RESTRICTED,"392,596.00"
296835,glasgow,PricewaterhouseCoopers LLP,OPEN,"715,564.00"
296836,portsmouth,Southdown Motor Services t/a Stagecoach in Por...,OPEN,"1,354,960.00"
296837,portsmouth,First Hampshire & Dorset Ltd,OPEN,"1,354,960.00"
296838,portsmouth,Southdown Motor Company / TA Stagecoach (South...,OPEN,"1,354,960.00"
296839,bromley,Baillie Gifford,RESTRICTED,nan
296840,bromley,Blackrock,RESTRICTED,nan
296841,bromley,MFS INTERNATIONAL (U.K.) LIMITED,RESTRICTED,nan
296842,birmingham,Arjo Huntleigh,RESTRICTED,nan
296843,birmingham,Direct Healthcare Services,RESTRICTED,nan
296844,birmingham,Frontier Medical Group,RESTRICTED,nan
296845,birmingham,Harvest Healthcare Ltd,RESTRICTED,nan
296846,birmingham,Hill-Rom,RESTRICTED,nan
296847,birmingham,Invacare Limited,RESTRICTED,nan
296848,birmingham,Karomed Limited,RESTRICTED,nan
296849,birmingham,Linet UK Limited,RESTRICTED,nan
296850,birmingham,Park House Healthcare Ltd,RESTRICTED,nan
296851,birmingham,Sumed International (UK) Limited,RESTRICTED,nan
296852,birmingham,Talley Group,RESTRICTED,nan
296853,middlesbrough,Park Retail,RESTRICTED,nan
296854,belfast,Airtricity Energy Supply Limited,OPEN,"14,084,507.00"
296855,larkhall,Gilead Sciences Ltd,NEGOTIATED_WITHOUT_PUBLICATION,"10,444,601.00"
296856,chippenham,Opus Energy Ltd,OPEN,nan
296857,harrow,Chubb Insurance Company of Europe SE,RESTRICTED,nan
296858,harrow,Zurich Municipal,RESTRICTED,nan
296859,crawley,Jackson Civil Engineering,RESTRICTED,"2,383,575.00"
296860,belfast,Flex Language Services Ltd,OPEN,nan
296861,belfast,STEP Training & Learning Ltd,OPEN,nan

In [77]:
df["tender_procedureType"].unique()

array(['OPEN', 'RESTRICTED', 'NEGOTIATED_WITHOUT_PUBLICATION', nan,
       'NEGOTIATED_WITH_PUBLICATION', 'COMPETITIVE_DIALOG', 'NEGOTIATED',
       'OTHER', 'OUTRIGHT_AWARD', 'INOVATION_PARTNERSHIP'], dtype=object)

In [78]:
df["tender_procedureType"].value_counts()
# df["tender_procedureType"].value_counts()["OPEN"]

OPEN                              187867
RESTRICTED                         74674
OTHER                               9276
NEGOTIATED_WITH_PUBLICATION         5802
NEGOTIATED_WITHOUT_PUBLICATION      4817
NEGOTIATED                          4167
COMPETITIVE_DIALOG                  1413
OUTRIGHT_AWARD                      1161
INOVATION_PARTNERSHIP                  4
Name: tender_procedureType, dtype: int64

In [79]:
df.describe()

,Unnamed: 0,tender_year,tender_mainCpv,bid_price,bid_price_EUR,tender_estimatedPrice,tender_estimatedPrice_EUR,tender_finalPrice,tender_finalPrice_EUR,tender_indicator_INTEGRITY_ADVERTISEMENT_PERIOD,tender_indicator_INTEGRITY_CALL_FOR_TENDER_PUBLICATION,tender_indicator_INTEGRITY_DECISION_PERIOD,tender_indicator_INTEGRITY_NEW_COMPANY,tender_indicator_INTEGRITY_PROCEDURE_TYPE,tender_indicator_INTEGRITY_SINGLE_BID,tender_indicator_INTEGRITY_TAX_HAVEN
count,"296,862.00","274,825.00","248,947.00","53,408.00","53,408.00","28,171.00","28,171.00","120,654.00","120,654.00","219,429.00","219,688.00","209,516.00","13,474.00","219,688.00","197,172.00","208,662.00"
mean,"26,499.09","2,013.97","59,178,900.12","14,278,358.90","14,278,358.90","38,530,239.14","38,530,239.14","41,451,108.43","41,451,108.43",53.38,53.39,83.04,43.90,95.20,80.39,99.85
std,"28,736.13",2.00,"20,968,732.85","82,569,383.50","82,569,383.50","114,581,140.69","114,581,140.69","121,719,145.30","121,719,145.30",49.89,49.89,37.53,49.63,21.38,39.71,3.84
min,0.00,"2,009.00","3,000,000.00",0.00,0.00,0.00,0.00,"135,007.00","135,007.00",0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,"10,253.00","2,012.00","44,113,050.00","63,183.00","63,183.00","1,121,391.00","1,121,391.00","910,056.00","910,056.00",0.00,0.00,100.00,0.00,100.00,100.00,100.00
50%,"21,319.00","2,014.00","60,120,000.00","368,192.50","368,192.50","5,451,097.00","5,451,097.00","4,113,111.00","4,113,111.00",100.00,100.00,100.00,0.00,100.00,100.00,100.00
75%,"32,908.00","2,016.00","79,310,000.00","1,972,093.25","1,972,093.25","21,745,039.00","21,745,039.00","17,238,599.00","17,238,599.00",100.00,100.00,100.00,100.00,100.00,100.00,100.00
max,"193,071.00","2,017.00","98,910,000.00","1,247,574,161.00","1,247,574,161.00","1,173,113,593.00","1,173,113,593.00","1,190,334,484.00","1,190,334,484.00",100.00,100.00,100.00,100.00,100.00,100.00,100.00

In [80]:
df[df["tender_procedureType"] == "COMPETITIVE_DIALOG"]

,Unnamed: 0,tender_id,tender_country,tender_year,tender_title,tender_mainCpv,tender_cpvs,tender_procedureType,buyer_id,buyer_name,...,tender_finalPrice_EUR,tender_finalPrice_currency,tender_indicator_INTEGRITY_ADVERTISEMENT_PERIOD,tender_indicator_INTEGRITY_CALL_FOR_TENDER_PUBLICATION,tender_indicator_INTEGRITY_DECISION_PERIOD,tender_indicator_INTEGRITY_NEW_COMPANY,tender_indicator_INTEGRITY_PROCEDURE_TYPE,tender_indicator_INTEGRITY_SINGLE_BID,tender_indicator_INTEGRITY_TAX_HAVEN,buyer_city_clean
557,2670,2f580bbe-2872-4818-9e90-6b4d8c38a845,UK,nan,UK - London contract for the provision of an e...,"48,000,000.00",48000000,COMPETITIVE_DIALOG,EU_body_3f4a44094a59620d52c009ec7aa1bc13b43263...,Lewisham Healthcare NHS Trust,...,"14,172,785.00",EUR,0.00,100.00,nan,100.00,100.00,nan,nan,london
666,3293,03bbc1dd-48e4-44de-baad-e04745aa3a66,UK,nan,UK: Management of Golden Lane Leisure Centre.,"92,000,000.00","92000000,45212290,92330000,79420000",COMPETITIVE_DIALOG,EU_body_7877a34e59f9f5a724da7a7768081fcc0aba1f...,City of London Corporation,...,"492,005.00",EUR,100.00,0.00,100.00,nan,100.00,100.00,100.00,london
1907,11259,7dd02fe1-720f-4f35-9842-b192a9b977af,UK,nan,Emergency Department Clinical Information and ...,"48,000,000.00","48000000,48814000,48180000,48814400,48814200,4...",COMPETITIVE_DIALOG,EU_body_b4718cd3414e963561b9a8e77e5a91e581b7c1...,Velindre NHS Trust (as hosts of the NHS Wales ...,...,nan,NaN,0.00,100.00,nan,nan,100.00,100.00,100.00,bridgend
2256,15911,694f65fb-7cb8-4786-8315-3e2e35b53a21,UK,nan,Theatre management system.,"48,000,000.00",48000000,COMPETITIVE_DIALOG,EU_body_f815f7a4d3ba8da5f02294941b5a263aaa429a...,Salisbury NHS Foundation Trust,...,"193,788.00",EUR,100.00,0.00,100.00,nan,100.00,nan,100.00,salisbury
2489,17240,5b251e25-bde6-46f1-82a3-ee3232173079,UK,nan,Auditing Services.,"79,212,000.00",79212000,COMPETITIVE_DIALOG,EU_body_8f60aa74858b55286acd301968ad9cfc26254a...,Dimensions (UK) Limited,...,nan,NaN,0.00,100.00,nan,nan,100.00,nan,100.00,theale
2490,17241,5b251e25-bde6-46f1-82a3-ee3232173079,UK,nan,Auditing Services.,"79,212,000.00",79212000,COMPETITIVE_DIALOG,EU_body_8f60aa74858b55286acd301968ad9cfc26254a...,Dimensions (UK) Limited,...,nan,NaN,0.00,100.00,nan,nan,100.00,nan,100.00,theale
2491,17242,5b251e25-bde6-46f1-82a3-ee3232173079,UK,nan,Auditing Services.,"79,212,000.00",79212000,COMPETITIVE_DIALOG,EU_body_8f60aa74858b55286acd301968ad9cfc26254a...,Dimensions (UK) Limited,...,nan,NaN,0.00,100.00,nan,nan,100.00,nan,100.00,theale
2831,25631,3f174d44-fa8e-4f62-8f2a-642e39a51e8e,UK,nan,Laundry Service to RBH - Provision of Laundry ...,"98,310,000.00","98310000,98311000,98311100,98311200,98312000,9...",COMPETITIVE_DIALOG,EU_body_b8c2fa1dd8087ff0093e2e2f18a76ba17807d7...,Bolton NHS Foundation Trust,...,nan,NaN,100.00,0.00,100.00,100.00,100.00,nan,nan,bolton
2950,26454,63daca85-bc3d-447d-9e26-0c4c3bcde165,UK,nan,"Stead Street, London SE17.","45,000,000.00",45000000,COMPETITIVE_DIALOG,EU_body_faa9d7499bfab4d20a97d407ec76920e5b2aa7...,Guinness Trustees Ltd (and/or any other associ...,...,nan,NaN,0.00,100.00,nan,nan,100.00,100.00,100.00,high wycombe
3189,29912,794bf223-376b-4f7a-8a6f-05def5c898ca,UK,nan,Primary Care Mental Health Service.,"85,000,000.00",85000000,COMPETITIVE_DIALOG,EU_body_b72daf250dca4e69018cfae2a2ea69b13aacb4...,NHS Ipswich and East Suffolk Clinical Commissi...,...,nan,NaN,0.00,100.00,nan,nan,100.00,nan,100.00,ipswich
3747,35030,d58eb84f-49b0-446f-9c60-36d501d372f0,UK,nan,Knowledge Management System.,"48,000,000.00","48000000,72000000,48222000,48200000,48220000,4...",COMPETITIVE_DIALOG,EU_body_467e8d4a266416a8dacf816aa41189647e4c04...,Tees Esk and Wear Valleys NHS Foundation Trust,...,"6,477,959.00",EUR,0.00,100.00,nan,100.00,100.00,0.00,100.00,county durham
3789,35383,bcb96a2b-455a-4476-b630-b59bdfa623b6,UK,nan,Bowburn Training Centre.,"45,000,000.00","45000000,35000000,35100000",COMPETITIVE_DIALOG,EU_body_146a3bf04acb277e0e3568db65baae2944fa5a...,The County Durham and Darlington Fire and Resc...,...,"6,512,906.00",EUR,0.00,100.00,nan,nan,100.00,100.00,100.00,durham
5080,42905,355cd2f0-a4e0-4427-9332-162a9d5dab8e,UK,nan,Integrated Healthy Lifestyles Service.,"85,000,000.00","85000000,85100000,85140000,85312300",COMPETITIVE_DIALOG,EU_body_1bae0c8745612c5d45732d64888cf1e542a353...,Suffolk County Council,...,nan,NaN,0.00,100.00,nan,nan,100.00,100.00,100.00,ipswich
5195,43845,0929b005-f6d7-476c-9784-f7ffad3d5f15,UK,nan,Walworth Business Park Rejuvenation Partner.,"70,112,000.00",70112000,COMPETITIVE_DIALOG,EU_body_2cd83b48d5dbad6235d891509409e00f652e07...,Test Valley Borough Council,...,nan,NaN,100.00,0.00,100.00,nan,100.00,100.00,100.00,andover
5280,44372,2dcd8498-272b-4fbf-9943-7d6ae1f8032b,UK,nan,Chichester District Council — Leisure Manageme...,"92,610,000.00",92610000,COMPETITIVE_DIALOG,EU_body_b130df12d23e2efc4175e409affeea85fadc8d...,Chichester District Council,...,nan,NaN,0.00,100.00,nan,nan,100.00,100.00,100.00,chichester
5307,44715,2d4fd8f9-c3a7-4778-b011-5bfe03c73fd1,UK,nan,Provision of insurance and claims handling ser...,"66,510,000.00","66510000,66512100,66512000,66514000,66519300,6...",COMPETITIVE_DIALOG,EU_body_974a04f2f12cfc54ed1c4ada0af9d5adebe961...,Rhondda Cynon Taf CBC,...,nan,NaN,100.00,0.00,100.00,nan,100.00,nan,100.00,porth
5308,44716,2d4fd8f9-c3a7-4778-b011-5bfe03c73fd1,UK,nan,Provision of insurance and claims handling ser...,"66,510,000.00","66510000,66512100,66512000,66514000,66519300,6...",COMPETITIVE_DIALOG,EU_body_974a04f2f12cfc54ed1c4ada0af9d5adebe961...,Rhondda Cynon Taf CBC,...,nan,NaN,100.00,0.00,100.00,nan,100.00,nan,100.00,porth
5309,44717,2d4fd8f9-c3a7-4778-b011-5bfe03c73fd1,UK,nan,Provision of insurance and claims handling ser...,"66,510,000.00","66510000,66512100,66512000,66514000,66519300,6...",COMPETITIVE_DIALOG,EU_body_974a04f2f12cfc54ed1c4ada0af9d5adebe961...,Rhondda Cynon Taf CBC,...,nan,NaN,100.00,0.00,100.00,nan,100.00,nan,100.00,porth
5543,46606,3ddf9141-668d-4e89-a21a-01894824c51a,UK,nan,Provision of Insurance Services.,"66,510,000.00",66510000,COMPETITIVE_DIALOG,EU_body_8f60aa74858b55286acd301968ad9cfc26254a...,Dimensions (UK) Limited,...,nan,NaN,0.00,100.00,nan,100.00,100.00,nan,nan,theale
5985,51233,53bcc480-35ba-48e7-81ff-6dbe5462565b,UK,nan,Order comms.,"72,000,000.00",72000000,COMPETITIVE_DIALOG,EU_body_f815f7a4d3ba8da5f02294941b5a263aaa429a...,Salisbury NHS Foundation Trust,...,"236,811.00",EUR,100.00,0.00,100.00,nan,100.00,nan,100.00,salisbury
6567,63092,9032b9c5-e220-4f6d-bc04-74b38106b7d7,UK,nan,"Integrated finance, procurement, human resourc...","72,212,451.00","72212451,72212440,72212450,79630000,72227000,7...",COMPETITIVE_DIALOG,EU_body_5e48c1e77a28093c87095054803a9d71623660...,Wokingham Borough Council,...,nan,NaN,100.00,0.00,100.00,nan,100.00,nan,100.00,wokingham
6584,63219,8c7bb8a7-91b1-4108-bbde-1887d21d0d2a,UK,nan,The Provision of a Renal Dialysis Satellite Un...,"85,100,000.00","85100000,85110000,85111900",COMPETITIVE_DIALOG,EU_body_2e4b3a4886a556549a4454633c816170115fe9...,The Newcastle upon Tyne Hospitals NHS Foundati...,...,nan,NaN,0.00,100.00,nan,nan,100.00,nan,100.00,newcastle upon tyne
7616,70487,e53647d7-ba90-4ded-8dcb-e684f20e03c1,UK,nan,Glasgow 2014 technology services integrator.,"72,000,000.00",72000000,COMPETITIVE_DIALOG,EU_body_69164707a3875977241819eb2d0c0cec752570...,Glasgow 2014 Limited,...,"2,348,107.00",EUR,0.00,100.00,nan,nan,100.00,nan,nan,glasgow
7690,70716,dcf18956-a21d-4f2f-947f-525e80570134,UK,nan,Tender for the provision of Website Developmen...,"72,000,000.00","72000000,72212220,72212200,72267000,72267100,7...",COMPETITIVE_DIALOG,EU_body_a7d0b2f7ee38372c3d7c4192d1f57b18c3966e...,Solihull College,...,nan,NaN,0.00,100.00,nan,nan,100.00,nan,100.00,solihull
8087,73955,bc7e925f-80ee-4475-a162-fcb06e593561,UK,nan,NHS Professionals Ltd — Insurance.,"66,510,000.00","66510000,66516000",COMPETITIVE_DIALOG,EU_body_d9e31f807a2a5606051dde77e21637214e9e13...,NHS Professionals Ltd,...,nan,NaN,100.00,0.00,100.00,100.00,100.00,nan,nan,watford
8237,75031,67b6f6fe-bf38-4811-a611-5910d98821cb,UK,nan,CPU-EU-040/2012 - Student Residence Accommodat...,"70,330,000.00","70330000,70210000,55250000,90911200,70311000,7...",COMPETITIVE_DIALOG,EU_body_e55c1534db0792e03bc82a539040a90631f141...,Kingston University,...,"2,487,268.00",EUR,0.00,100.00,nan,nan,100.00,nan,100.00,kingston upon thames
8283,75267,e91d388a-02dd-493b-a152-f411a23ad530,UK,nan,Fleet and Associated Vehicle Equipment Mainten...,"50,110,000.00",50110000,COMPETITIVE_DIALOG,EU_body_f4b4c7230262c4a8f5455ebacccbcb2ea2e82b...,Derbyshire Fire & Rescue Service,...,nan,NaN,100.00,100.00,nan,nan,100.00,100.00,100.00,derby
8740,78406,140e406d-ef6c-402c-acb0-1480f91307e1,UK,nan,Establishment of a procurement shared service ...,"73,000,000.00",73000000,COMPETITIVE_DIALOG,EU_body_3570d3c46752fef88de2947d7aae75147a32e2...,Dorset Police,...,nan,NaN,100.00,0.00,100.00,nan,100.00,nan,100.00,dorchester
8884,79793,0376bfc2-b4c5-4a0e-8c1d-ca85e4246473,UK,nan,Residual Waste Treatment and Disposal.,"90,513,100.00","90513100,90513000,90513200,90513300,90512000,4...",COMPETITIVE_DIALOG,EU_body_87b77eadb81d1d9354aca3af6aac336c4a05f2...,Cheshire West and Chester,...,nan,NaN,100.00,0.00,100.00,nan,100.00,nan,100.00,chester
9819,86265,3cbc9cbb-b5d4-4f1c-b8a3-a5ca5d8336c4,UK,nan,RBCS Commissioning Programme.,"50,312,600.00","50312600,66172000,72300000,72611000,75100000,7...",COMPETITIVE_DIALOG,EU_body_c8a39a60fc6fcae65cf3e7bfae268fae5955eb...,London Borough of Lambeth,...,nan,NaN,100.00,0.00,100.00,100.00,100.00,nan,nan,london
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291522,32201,526b6bf3-9a1b-430d-bcd8-73c48ea1f5bd,UK,"2,013.00",ICT Infrastructure Services.,"72,000,000.00","72000000,72510000,72540000,72611000,72910000,7...",COMPETITIVE_DIALOG,EU_body_3d43bf36b13f442f169b0e761c0d05d3d74fe0...,Central and North West London NHS Foundation T...,...,"74,633,950.00",EUR,0.00,100.00,0.00,nan,100.00,100.00,100.00,london
291539,32219,57dd6699-23fc-4517-891e-323286dc48eb,UK,"2,013.00",Digital Districts: Next Generation Wireless Co...,"32,412,000.00","32412000,32412100,32412110,32424000,32510000,3...",COMPETITIVE_DIALOG,EU_body_84d324c675f875548e6016c78bcd8b169b1777...,Birmingham City Council,...,nan,NaN,100.00,0.00,100.00,nan,100.00,nan,100.00,birmingham
291567,32254,5dcfaee1-2565-4bc4-b44b-7b8374276565,UK,"2,013.00",Contract to establish and support an Employee-...,"79,400,000.00","79400000,79420000,79411000,80000000,51610000,7...",COMPETITIVE_DIALOG,EU_body_1d4ccac44fa64eef87fe509078c2490c178953...,London Borough of Hammersmith and Fulham,...,nan,NaN,0.00,100.00,100.00,nan,100.00,nan,100.00,london
291708,32408,624063ca-84b0-44e6-8b7d-6e06afddf549,UK,"2,013.00",Essex County Council Leased Motor Tender,"66,514,110.00","66514110,66510000",COMPETITIVE_DIALOG,EU_body_7f6c37eda845e90fb79d27f73e80ae83c2eebc...,Essex County Council,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,chelmsford
291827,32543,71bc5a69-01b2-4447-8c8b-4163faee439d,UK,"2,013.00",Supply & implementation of server virtualisati...,"72,500,000.00","72500000,72212900",COMPETITIVE_DIALOG,EU_body_1ebc1d46a88b3e786f56a99969c805c8dc1ede...,Futures Housing Group,...,"193,080.00",EUR,0.00,100.00,100.00,nan,100.00,100.00,100.00,derby
292420,33152,3e654b82-9d8b-45c1-a11c-827c8e72aaa8,UK,"2,013.00",Public Realm Services.,"90,000,000.00","90000000,90500000,90610000,77314000,90511000,9...",COMPETITIVE_DIALOG,EU_body_cc0dc8eac966e38621d1f25a43a4d0d94d820a...,London Borough of Brent,...,"174,725,275.00",EUR,0.00,100.00,0.00,nan,100.00,0.00,100.00,wembley
292976,33777,8b3aaf89-c4ed-4728-8211-51858c1447fc,UK,"2,013.00",Business Operations and Enforcement Operations.,"72,000,000.00","72000000,63712000,48100000,79990000,98351110,3...",COMPETITIVE_DIALOG,EU_body_9ec14c0a1ee3f7b0a52e46f5fcab49b6479946...,Transport for London - Surface Transport,...,"175,992,232.00",EUR,0.00,100.00,100.00,100.00,100.00,nan,100.00,london
293675,34546,99812852-6149-4735-a072-6c190027b785,UK,"2,013.00",Royal College of Art - Phase 3 Woo Building.,"45,214,000.00","45214000,45214400",COMPETITIVE_DIALOG,EU_body_ba170755c7d039b384f537fb20ef534dc90484...,Royal College of Art Design Group Limited,...,"9,918,898.00",EUR,0.00,100.00,0.00,nan,100.00,100.00,100.00,london
293677,34548,998886a3-c5f5-4e78-bc5b-6806101b1dce,UK,"2,013.00",Supply of Building Materials and Tool Hire.,"44,000,000.00",44000000,COMPETITIVE_DIALOG,EU_body_9aee3c2c2388bbdc04e2ae3d989072a69fcbf0...,Derwentside Homes Limited,...,nan,NaN,100.00,0.00,100.00,nan,100.00,100.00,100.00,stanley
294839,35749,a5ce51b8-34d9-4321-8366-633b08b37a3d,UK,"2,013.00",AfricaConnect Equipment 2012.,"32,500,000.00",32500000,COMPETITIVE_DIALOG,EU_body_5a829012ad5ee23b17ad10ab3eac5282ea8d03...,Delivery of Advanced Network Technology to Eur...,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,cambridge
295099,36043,ad7f587e-6218-4aca-80e3-b598a364dda3,UK,"2,013.00",Re-development of Former Hilsea Bus Depot Site...,"45,211,341.00","45211341,45213100,45213112",COMPETITIVE_DIALOG,EU_body_d2273e75a60fda91dd68688e10159904af5a06...,"Redevelopment of Former Hilsea Bus Depot, Port...",...,"12,411,189.00",EUR,100.00,0.00,100.00,nan,100.00,100.00,100.00,portsmouth
295199,36169,db3981d1-2e98-421b-870d-27ae3c44cc1f,UK,"2,013.00",Warm Up North.,"79,400,000.00","79400000,71314300,71314000,71314200,79342000,7...",COMPETITIVE_DIALOG,EU_body_0b05059db9c106684b8fbc58ec37651218f280...,Newcastle City Council,...,"237,529,691.00",EUR,0.00,100.00,100.00,nan,100.00,100.00,100.00,newcastle upon tyne
295370,36340,e4cb2107-7fc7-4bce-b698-900681a9b958,UK,"2,013.00",Insurance and Claims Management (excluding Ins...,"66,510,000.00","66510000,66515200,66513200,66515411,66516000,6...",COMPETITIVE_DIALOG,EU_body_5d710399261b719ad562dcdc2be35613318b4a...,Leicester City Council,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,leicester
295371,36341,e4cb2107-7fc7-4bce-b698-900681a9b958,UK,"2,013.00",Insurance and Claims Management (excluding Ins...,"66,510,000.00","66510000,66515200,66513200,66515411,66516000,6...",COMPETITIVE_DIALOG,EU_body_5d710399261b719ad562dcdc2be35613318b4a...,Leicester City Council,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,leicester
295372,36342,e4cb2107-7fc7-4bce-b698-900681a9b958,UK,"2,013.00",Insurance and Claims Management (excluding Ins...,"66,510,000.00","66510000,66515200,66513200,66515411,66516000,6...",COMPETITIVE_DIALOG,EU_body_5d710399261b719ad562dcdc2be35613318b4a...,Leicester City Council,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,leicester
295373,36343,e4cb2107-7fc7-4bce-b698-900681a9b958,UK,"2,013.00",Insurance and Claims Management (excluding Ins...,"66,510,000.00","66510000,66515200,66513200,66515411,66516000,6...",COMPETITIVE_DIALOG,EU_body_5d710399261b719ad562dcdc2be35613318b4a...,Leicester City Council,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,leicester
295374,36344,e4cb2107-7fc7-4bce-b698-900681a9b958,UK,"2,013.00",Insurance and Claims Management (excluding Ins...,"66,510,000.00","66510000,66515200,66513200,66515411,66516000,6...",COMPETITIVE_DIALOG,EU_body_5d710399261b719ad562dcdc2be35613318b4a...,Leicester City Council,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,leicester
295375,36345,e4cb2107-7fc7-4bce-b698-900681a9b958,UK,"2,013.00",Insurance and Claims Management (excluding Ins...,"66,510,000.00","66510000,66515200,66513200,66515411,66516000,6...",COMPETITIVE_DIALOG,EU_body_5d710399261b719ad562dcdc2be35613318b4a...,Leicester City Council,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,leicester
295376,36346,e4cb2107-7fc7-4bce-b698-900681a9b958,UK,"2,013.00",Insurance and Claims Management (excluding Ins...,"66,510,000.00","66510000,66515200,66513200,66515411,66516000,6...",COMPETITIVE_DIALOG,EU_body_5d710399261b719ad562dcdc2be35613318b4a...,Leicester City Council,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,leicester
295584,36569,e86bd1ab-c066-42dc-8292-9f33fcbd8edf,UK,"2,013.00",Business transaction and personal business sof...,"48,400,000.00",48400000,COMPETITIVE_DIALOG,EU_body_31c83002cc42ae7aafc7ce493192a94ab2025b...,Surrey Heath Botrough Council,...,nan,NaN,100.00,0.00,100.00,nan,100.00,100.00,100.00,camberley
295859,36885,b21e2d29-b74c-4247-a972-3c81e9a29dab,UK,"2,013.00",0389 - PPSA - Non Emergency Patient Transport ...,"34,114,122.00","34114122,60120000,60130000,60171000,85110000",COMPETITIVE_DIALOG,EU_body_b8a9d9670194f42f5ad14914f431b36a184422...,NHS Wiltshire Clinical Commissioning Group,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,devizes
295860,36886,b21e2d29-b74c-4247-a972-3c81e9a29dab,UK,"2,013.00",0389 - PPSA - Non Emergency Patient Transport ...,"34,114,122.00","34114122,60120000,60130000,60171000,85110000",COMPETITIVE_DIALOG,EU_body_b8a9d9670194f42f5ad14914f431b36a184422...,NHS Wiltshire Clinical Commissioning Group,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,devizes
295861,36887,b21e2d29-b74c-4247-a972-3c81e9a29dab,UK,"2,013.00",0389 - PPSA - Non Emergency Patient Transport ...,"34,114,122.00","34114122,60120000,60130000,60171000,85110000",COMPETITIVE_DIALOG,EU_body_b8a9d9670194f42f5ad14914f431b36a184422...,NHS Wiltshire Clinical Commissioning Group,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,devizes
295862,36888,b21e2d29-b74c-4247-a972-3c81e9a29dab,UK,"2,013.00",0389 - PPSA - Non Emergency Patient Transport ...,"34,114,122.00","34114122,60120000,60130000,60171000,85110000",COMPETITIVE_DIALOG,EU_body_b8a9d9670194f42f5ad14914f431b36a184422...,NHS Wiltshire Clinical Commissioning Group,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,devizes
296084,37132,cca02883-ae87-43be-9826-9b107138cff1,UK,"2,013.00",Adult Drug Treatment Service.,"85,100,000.00",85100000,COMPETITIVE_DIALOG,EU_body_434152754dc2d4d4bfe7f41e68affb9ad46020...,Sandwell Metropolitan Borough Council,...,"11,843,131.00",EUR,100.00,0.00,100.00,nan,100.00,100.00,100.00,oldbury
296085,37133,cca02883-ae87-43be-9826-9b107138cff1,UK,"2,013.00",Adult Drug Treatment Service.,"85,100,000.00",85100000,COMPETITIVE_DIALOG,EU_body_434152754dc2d4d4bfe7f41e68affb9ad46020...,Sandwell Metropolitan Borough Council,...,"11,843,131.00",EUR,100.00,0.00,100.00,nan,100.00,100.00,100.00,oldbury
296128,37178,c8560d59-6e6b-4e19-8e55-f99c827378c9,UK,"2,013.00","C334.11 - National Water Sports Centre Manage,...","79,993,100.00","79993100,92000000,92610000,70332200",COMPETITIVE_DIALOG,EU_body_36cde18a00b8754eab5b0151542cf6a1e4617c...,Nottinghamshire County Council,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,nottingham
296478,37541,b9939ecc-40d6-4cc6-b22e-7c57238dad74,UK,"2,013.00",Brunswick HRA Housing PFI Contract (aka The Br...,"70,333,000.00","70333000,45111000,71240000",COMPETITIVE_DIALOG,EU_body_93f170292edc18c7a8338fbd717cb18b072217...,Manchester City Council,...,"308,155,281.00",EUR,100.00,0.00,100.00,nan,100.00,100.00,100.00,manchester
296488,37552,bc532580-6717-4a93-aef8-7e8cc079685e,UK,"2,013.00",A77 Symington and Bogend Toll Improvements.,"45,233,100.00","45233100,45233120,45233124,45233126,45221111,4...",COMPETITIVE_DIALOG,EU_body_ed97a35237ffa188ae11d42d73df6f91804a73...,Transport Scotland on behalf of the Scottish M...,...,"12,389,560.00",EUR,0.00,100.00,0.00,nan,100.00,100.00,100.00,glasgow
296511,37580,f8f849af-b9e7-4ae8-b7c2-5c090fd8a7b4,UK,"2,013.00",Provision of a Dementia Resource Centre and as...,"85,000,000.00",85000000,COMPETITIVE_DIALOG,EU_body_e54efc7c71bf10fbd0067bfe7e82c35bb7b236...,Peterborough City Council,...,"1,773,071.00",EUR,100.00,0.00,100.00,nan,100.00,100.00,100.00,peterborough

In [81]:
df[df["tender_procedureType"].str.contains("NEGOTIATED").fillna(False)]

,Unnamed: 0,tender_id,tender_country,tender_year,tender_title,tender_mainCpv,tender_cpvs,tender_procedureType,buyer_id,buyer_name,...,tender_finalPrice_EUR,tender_finalPrice_currency,tender_indicator_INTEGRITY_ADVERTISEMENT_PERIOD,tender_indicator_INTEGRITY_CALL_FOR_TENDER_PUBLICATION,tender_indicator_INTEGRITY_DECISION_PERIOD,tender_indicator_INTEGRITY_NEW_COMPANY,tender_indicator_INTEGRITY_PROCEDURE_TYPE,tender_indicator_INTEGRITY_SINGLE_BID,tender_indicator_INTEGRITY_TAX_HAVEN,buyer_city_clean
38,326,14f01ff9-ae5f-42b5-93d6-a55ea8e5bb26,UK,nan,Tender for the provision of legal services eje...,"79,000,000.00","79000000,79100000,79110000",NEGOTIATED_WITHOUT_PUBLICATION,EU_body_aba123a9b46c140bcf95a610d517cd9c3766f6...,Northern Ireland Housing Executive,...,nan,NaN,100.00,0.00,100.00,nan,0.00,nan,100.00,belfast
39,327,14f01ff9-ae5f-42b5-93d6-a55ea8e5bb26,UK,nan,Tender for the provision of legal services eje...,"79,000,000.00","79000000,79100000,79110000",NEGOTIATED_WITHOUT_PUBLICATION,EU_body_aba123a9b46c140bcf95a610d517cd9c3766f6...,Northern Ireland Housing Executive,...,nan,NaN,100.00,0.00,100.00,nan,0.00,nan,100.00,belfast
40,328,14f01ff9-ae5f-42b5-93d6-a55ea8e5bb26,UK,nan,Tender for the provision of legal services eje...,"79,000,000.00","79000000,79100000,79110000",NEGOTIATED_WITHOUT_PUBLICATION,EU_body_aba123a9b46c140bcf95a610d517cd9c3766f6...,Northern Ireland Housing Executive,...,nan,NaN,100.00,0.00,100.00,nan,0.00,nan,100.00,belfast
135,914,0bef16f1-3517-4e00-bac0-24b344e523c6,UK,nan,DAC 244/14 DVA Taxi Plating Consumables.,"22,458,000.00","22458000,60120000,22454000",NEGOTIATED_WITHOUT_PUBLICATION,EU_body_9c98f340b29af6480765be86dd77cd7b7cae37...,"Department of the Environment, Driver and Vehi...",...,"195,736.00",EUR,100.00,0.00,100.00,nan,0.00,nan,100.00,belfast
188,1198,1cb27c36-a799-40d1-a016-369d02e25cb1,UK,nan,Woodland and Countryside Management Services.,"77,231,000.00","77231000,71420000",NEGOTIATED_WITH_PUBLICATION,EU_body_5f01876458414b519d6706aa18e05ebf8fd2a3...,Yorkshire Water Services Limited,...,"10,545,742.00",EUR,100.00,0.00,100.00,nan,0.00,100.00,100.00,bradford
209,1279,208bd4ab-70da-4156-9cf4-9e7e356b63bf,UK,nan,TRGACC/1050.,"32,230,000.00",32230000,NEGOTIATED_WITHOUT_PUBLICATION,EU_body_b37861aab902826be6d954bf9b734b1d0edc3f...,"Training Aircraft (TA), DE&S",...,nan,NaN,100.00,0.00,100.00,100.00,0.00,nan,nan,huntingdon
634,3106,2b580e47-344a-459b-abad-bc44e061a233,UK,nan,Plant maintenance services of road / Rail exca...,"60,200,000.00",60200000,NEGOTIATED,EU_body_d899ba18ea069cac619972543725ede38e2711...,Translink,...,nan,NaN,0.00,100.00,nan,nan,100.00,0.00,100.00,belfast
705,3534,0178d115-2720-4296-b0f4-168883331b43,UK,nan,TfL Signage and Display Framework tfl_scp_001256.,"34,928,470.00","34928470,34992000,31523000,31523200,34924000,4...",NEGOTIATED_WITH_PUBLICATION,EU_body_0ae054bbf90703c242fef630300352300103d3...,Transport for London — Commercial Surface,...,"47,189,288.00",EUR,100.00,0.00,100.00,nan,0.00,100.00,100.00,london
706,3535,0178d115-2720-4296-b0f4-168883331b43,UK,nan,TfL Signage and Display Framework tfl_scp_001256.,"34,928,470.00","34928470,34992000,31523000,31523200,34924000,4...",NEGOTIATED_WITH_PUBLICATION,EU_body_0ae054bbf90703c242fef630300352300103d3...,Transport for London — Commercial Surface,...,"47,189,288.00",EUR,100.00,0.00,100.00,nan,0.00,100.00,100.00,london
707,3536,0178d115-2720-4296-b0f4-168883331b43,UK,nan,TfL Signage and Display Framework tfl_scp_001256.,"34,928,470.00","34928470,34992000,31523000,31523200,34924000,4...",NEGOTIATED_WITH_PUBLICATION,EU_body_0ae054bbf90703c242fef630300352300103d3...,Transport for London — Commercial Surface,...,"47,189,288.00",EUR,100.00,0.00,100.00,nan,0.00,100.00,100.00,london
708,3537,0178d115-2720-4296-b0f4-168883331b43,UK,nan,TfL Signage and Display Framework tfl_scp_001256.,"34,928,470.00","34928470,34992000,31523000,31523200,34924000,4...",NEGOTIATED_WITH_PUBLICATION,EU_body_0ae054bbf90703c242fef630300352300103d3...,Transport for London — Commercial Surface,...,"47,189,288.00",EUR,100.00,0.00,100.00,nan,0.00,100.00,100.00,london
713,3542,018f84b6-dd2c-4f55-b98c-5969b63297d4,UK,nan,Insurance.,"66,510,000.00",66510000,NEGOTIATED,EU_body_2bf3ed46ad064c92e97aa59c901bee8614545a...,Bromsgrove District Housing Trust,...,nan,NaN,0.00,100.00,nan,nan,100.00,nan,100.00,bromsgrove
776,3980,0528acb8-c353-422a-b952-98d864155318,UK,nan,NW725 Alternative Water Supplies.,"65,100,000.00",65100000,NEGOTIATED_WITH_PUBLICATION,EU_body_42df0baa708b4ff3a2245885a45a083b273b53...,Northumbrian Water Limited,...,nan,NaN,100.00,0.00,100.00,100.00,0.00,nan,nan,durham
794,4118,230e1d0f-80ae-4401-96d4-90ae8b1cf9bb,UK,nan,Stalybridge re-control main works.,"45,234,115.00",45234115,NEGOTIATED_WITH_PUBLICATION,EU_body_1bcbc403a7d7416e29138af7abed92057439eb...,Network Rail Infrastructure Limited,...,nan,NaN,100.00,0.00,100.00,nan,0.00,nan,100.00,london
1046,5978,8aa8d582-3369-47b3-b428-68e3c5dc1a8b,UK,nan,Provision of fully managed Emergency Fire Crew...,"75,251,100.00",75251100,NEGOTIATED_WITHOUT_PUBLICATION,EU_body_620786724fb90af8b69f137370a77aa6fe3e32...,London Fire and Emergency Planning Authority,...,nan,NaN,100.00,0.00,100.00,nan,0.00,nan,100.00,london
1055,6058,9069c9c9-dc04-4240-bc0a-dda9e7e69666,UK,nan,Tornado Collision Warning System.,"34,741,000.00",34741000,NEGOTIATED_WITHOUT_PUBLICATION,EU_body_e42c788fc095c47d6954cc6917f9e517e97294...,"Fast Air Support Team (FAST), DE&S",...,"44,359,190.00",EUR,100.00,0.00,100.00,nan,0.00,nan,100.00,bristol
1154,6645,9a95a8a4-1f50-48c5-9d21-331a2482157d,UK,nan,Spares Inclusive Repair Plus Post Design Servi...,"71,300,000.00",71300000,NEGOTIATED_WITHOUT_PUBLICATION,EU_body_78d20c080ddb2d7afadb5a5a5de2e60e47ea14...,"Ministry of Defence, Air Support, Air Commodit...",...,"1,902,691.00",EUR,100.00,0.00,100.00,nan,0.00,nan,100.00,bristol
1165,6743,9ebfe935-17b9-4b13-9ded-0cf37c93f2e4,UK,nan,PRef - 2012.09.18-CS - Coaching Services.,"80,000,000.00","80000000,80510000,80511000,80530000,80532000,8...",NEGOTIATED_WITH_PUBLICATION,EU_body_d1f4a8cb68cd661367607359ea1821af77b592...,Magnox Limited,...,"687,049.00",EUR,100.00,0.00,100.00,nan,0.00,nan,100.00,gloucestershire
1221,7012,a624e394-1d17-45a3-8495-a5e3c5680afd,UK,nan,PA 2010 0038 In House Display Units - To work ...,"32,000,000.00",32000000,NEGOTIATED_WITH_PUBLICATION,EU_body_540e202f0d423fdcaae0097d2cfb5a1656ee5d...,Anglian Water Services Ltd,...,nan,NaN,100.00,0.00,100.00,100.00,0.00,nan,nan,peterborough
1244,7088,a5ad4efa-49a9-415a-a249-d31a2872540d,UK,nan,Leeds Transport Model Mark II — Development an...,"79,410,000.00",79410000,NEGOTIATED_WITHOUT_PUBLICATION,EU_body_7f34c6ea47528978a43e22fbb0f4d96425295e...,West Yorkshire Combined Authority,...,"878,260.00",EUR,100.00,0.00,100.00,nan,0.00,0.00,100.00,leeds
1266,7278,a1046d91-1cce-4012-9f4d-38d124613e23,UK,nan,MAG 1092 — IT Hardware Procurement Framework A...,"72,000,000.00","72000000,48820000,30230000,30110000,30210000,3...",NEGOTIATED_WITH_PUBLICATION,EU_body_3fc7bd3a60494cef6a7210f7e36bdff0fd52e2...,The Manchester Airport Group PLC,...,nan,NaN,100.00,0.00,100.00,100.00,0.00,nan,100.00,manchester
1539,9258,94eb9925-5c77-46e6-b0b2-9873d4a1dcf4,UK,nan,Provision of bus service - route 462.,"60,112,000.00",60112000,NEGOTIATED_WITH_PUBLICATION,EU_body_d2f512974fc8b11739a92f62a9a742b9cf6689...,London Bus Services Limited,...,"1,969,582.00",EUR,100.00,0.00,100.00,nan,0.00,nan,100.00,london
1641,9696,acc64c03-7389-41cd-b4e0-a9b9bf15d035,UK,nan,F426-10 Reservoir Kiosk Enhancement Programme.,"44,610,000.00",44610000,NEGOTIATED_WITH_PUBLICATION,EU_body_78ddfa3a5079e2e49450ca762c4c25326a99ae...,Southern Water Services Limited,...,nan,NaN,100.00,0.00,100.00,100.00,0.00,nan,nan,worthing
1700,10009,b1bd03f4-c922-48f1-9785-a25b6f1307bb,UK,nan,Insurance services review 2011.,"66,510,000.00",66510000,NEGOTIATED_WITH_PUBLICATION,EU_body_f3f87037d67e528d9bcfbe195c9b2fa50de254...,Vale of Aylesbury Housing Trust,...,nan,NaN,100.00,0.00,100.00,nan,0.00,100.00,100.00,aylesbury
1831,10395,7f6cc2c9-1c2e-46fd-917f-3d8e614d4665,UK,nan,"Barrier boards, cones and road signs.","34,928,000.00",34928000,NEGOTIATED_WITH_PUBLICATION,EU_body_d911592cb1c4d60fd3c13a65befa81fc4832ee...,Northumbrian Water Ltd,...,nan,NaN,100.00,0.00,100.00,nan,0.00,100.00,100.00,durham
1848,10557,7c6ea8e4-5794-4450-91d5-2b00d66a83a6,UK,nan,Contracts for management services for EAIF and...,"66,000,000.00",66000000,NEGOTIATED_WITH_PUBLICATION,EU_body_0232ec3ab5a768878a8447b37226ea60b5964f...,MDY Legal acting as agent for and on behalf of...,...,nan,NaN,100.00,0.00,100.00,100.00,0.00,nan,nan,london
1926,11426,83002f64-3062-43d2-aed1-74557568c49b,UK,nan,Technology improvement programme.,"32,424,000.00","32424000,32428000,32571000,72610000,72590000,7...",NEGOTIATED_WITH_PUBLICATION,EU_body_6fbbfd756897b3022035ce8837e4f0ce0b9e46...,Sussex Partnership NHS Foundation Trust,...,"44,592,862.00",EUR,100.00,0.00,100.00,nan,0.00,100.00,100.00,worthing
1928,11444,81872187-c4cc-42c0-a0fe-1f18bf951537,UK,nan,Beauly Denny 132kV Towers & Access Works.,"65,300,000.00","65300000,45111000",NEGOTIATED_WITH_PUBLICATION,EU_body_7aca7d65da2c9a1129d15d2189509389265783...,SP Power Systems Limited,...,nan,NaN,100.00,0.00,100.00,nan,0.00,100.00,100.00,glasgow
1949,11594,8a2b5daf-ed56-4232-bcc2-b31ccdc90da9,UK,nan,Provision of Staff Catering Facilities (Restau...,"55,520,000.00","55520000,55510000",NEGOTIATED_WITH_PUBLICATION,EU_body_367022d58cbe706ac9d0bcfc632b198d091b30...,Eurotunnel,...,nan,NaN,100.00,0.00,100.00,100.00,0.00,nan,nan,folkestone
1982,11793,86ca650e-1e76-417e-bc56-9f5780318c06,UK,nan,Provision of Property Management Services.,"70,330,000.00",70330000,NEGOTIATED_WITH_PUBLICATION,EU_body_989aff51286418bfa2616f1bc70db0678bd2db...,Go Ahead Group Holding,...,nan,NaN,100.00,0.00,100.00,100.00,0.00,nan,100.00,london
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296087,37137,cce773f5-5a02-441a-a719-f362df404436,UK,"2,013.00",Provision of Bus Service — Route 8/N8.,"60,112,000.00",60112000,NEGOTIATED_WITH_PUBLICATION,EU_body_d2f512974fc8b11739a92f62a9a742b9cf6689...,London Bus Services Limited,...,"9,561,991.00",EUR,100.00,0.00,100.00,nan,0.00,0.00,100.00,london
296121,37171,c6c189d1-8a18-40eb-a72d-15f879a9f266,UK,"2,013.00",Provision of Bus Service - Route 272.,"60,112,000.00",60112000,NEGOTIATED_WITH_PUBLICATION,EU_body_d2f512974fc8b11739a92f62a9a742b9cf6689...,London Bus Services Limited,...,"2,100,104.00",EUR,100.00,0.00,100.00,nan,0.00,0.00,100.00,london
296341,37391,e9b7f855-00b9-4b09-813b-ad4f5feb9d93,UK,"2,013.00",Custody Medical Services.,"85,141,000.00","85141000,85141200",NEGOTIATED_WITHOUT_PUBLICATION,EU_body_6c4d5297b3ef1199abbbe7d13f01964fc8df6f...,Cumbria Constabulary,...,"2,198,081.00",EUR,100.00,0.00,100.00,nan,0.00,100.00,100.00,penrith
296353,37410,ee5fcce3-df39-48e6-a02f-b1239443002b,UK,"2,013.00",Redwell Primary School.,"45,214,000.00",45214000,NEGOTIATED_WITHOUT_PUBLICATION,EU_body_ebfd365a0943c4c2ca119344cdd604e471dd45...,Clackmannanshire Council,...,"9,676,489.00",EUR,100.00,0.00,100.00,nan,0.00,0.00,100.00,alloa
296358,37418,ef21b947-6bba-4afa-b166-070bcd7446b0,UK,"2,013.00",Contract for the Provision of Logisitics Services,"63,120,000.00",63120000,NEGOTIATED_WITH_PUBLICATION,EU_body_fd9023831cc45532741edeaf2ccb3d683a7f69...,National Grid UK Ltd,...,nan,NaN,100.00,0.00,100.00,nan,0.00,100.00,100.00,london
296362,37422,bfc333fb-2924-40b6-ae8c-c7ac4db15bec,UK,"2,013.00",Post Design Services and Contractor Logistic S...,"80,660,000.00",80660000,NEGOTIATED_WITHOUT_PUBLICATION,EU_body_0cfd430a0080310ae8b2fc163ef9e76d4b0d1e...,"Joint & Battlefield Trainers, Simulation & Syn...",...,"4,777,026.00",EUR,100.00,0.00,100.00,nan,0.00,nan,100.00,bristol
296368,37431,c001a01d-635a-476e-8be0-af24259dc8ea,UK,"2,013.00",NCA_0059_Flowwave_ENG_LT_0513.,"31,120,000.00",31120000,NEGOTIATED_WITHOUT_PUBLICATION,EU_body_1d2b70c4b5ea7615b46995e4cbf160b0c09269...,University Of Edinburgh,...,"241,971.00",EUR,100.00,0.00,100.00,100.00,0.00,0.00,100.00,edinburgh
296446,37509,b75ddd8e-a9bf-4ea6-ab9d-b70321937e34,UK,"2,013.00",Wakefield MDC - Waste Management PFI Project,"90,000,000.00","90000000,90500000,90510000,90514000,45000000",NEGOTIATED_WITH_PUBLICATION,EU_body_7c91988139403a42a2b5c558a0441e0473d1d3...,Council of the City of Wakefield Council,...,nan,NaN,100.00,0.00,100.00,nan,0.00,100.00,100.00,wakefield
296483,37547,b59a7b6b-3b46-4e5b-b0c8-c4a8727ff637,UK,"2,013.00","Dementia Advisor Service, Winchester.","85,000,000.00",85000000,NEGOTIATED_WITHOUT_PUBLICATION,EU_body_ab05c2b22c0ae656b075bf03063b6263b3c599...,Hampshire County Council,...,"640,309.00",EUR,100.00,0.00,100.00,nan,0.00,nan,100.00,winchester
296485,37549,bb109c11-21e7-4f59-b4cb-8946e6b89ba7,UK,"2,013.00","13/09 Financial Well-Being, Debt and Generalis...","85,312,300.00",85312300,NEGOTIATED_WITHOUT_PUBLICATION,EU_body_5658b1cfba824887b0aa8f159dffa542974e76...,Tamworth Borough Council,...,"216,151.00",EUR,100.00,0.00,100.00,nan,0.00,100.00,100.00,tamworth staffs
296501,37570,d3c8f6fa-b702-4b1e-923c-3ed630ee33a5,UK,"2,013.00",Purchase Of TR Cells,"31,410,000.00",31410000,NEGOTIATED_WITH_PUBLICATION,EU_body_d6c9b8f3e6afbf72d97a3ac8aabd06bf15899c...,Air Defence & Air Traffic Systems Delivery Tea...,...,"903,719.00",EUR,100.00,0.00,100.00,nan,0.00,0.00,100.00,henlow
296512,37581,f540798a-02b2-48d0-b576-9f95b40976d6,UK,"2,013.00",DMC111 - Shared Housing with support for young...,"85,311,000.00",85311000,NEGOTIATED_WITHOUT_PUBLICATION,EU_body_9553b942f50885e558cf1037caa0a3ce121edf...,Shropshire Council,...,"304,816.00",EUR,100.00,0.00,100.00,nan,0.00,100.00,100.00,shrewsbury
296543,37612,f4b94106-17db-4cfd-aecb-b96f5ab9c7a1,UK,"2,013.00",Non Medical Pre Registration Education and Tra...,"80,561,000.00",80561000,NEGOTIATED_WITHOUT_PUBLICATION,EU_body_99cc3597d27e568ad4b04e65f8a019bfa251f0...,National Leadership and Innovation Agency for ...,...,nan,NaN,100.00,0.00,100.00,nan,0.00,100.00,nan,llanharan
296544,37613,f4b94106-17db-4cfd-aecb-b96f5ab9c7a1,UK,"2,013.00",Non Medical Pre Registration Education and Tra...,"80,561,000.00",80561000,NEGOTIATED_WITHOUT_PUBLICATION,EU_body_99cc3597d27e568ad4b04e65f8a019bfa251f0...,National Leadership and Innovation Agency for ...,...,nan,NaN,100.00,0.00,100.00,nan,0.00,100.00,nan,llanharan
296545,37614,f4b94106-17db-4cfd-aecb-b96f5ab9c7a1,UK,"2,013.00",Non Medical Pre Registration Education and Tra...,"80,561,000.00",80561000,NEGOTIATED_WITHOUT_PUBLICATION,EU_body_99cc3597d27e568ad4b04e65f8a019bfa251f0...,National Leadership and Innovation Agency for ...,...,nan,NaN,100.00,0.00,100.00,nan,0.00,100.00,nan,llanharan
296554,37623,f4292c95-a913-45fc-80f2-c179e2b2d875,UK,"2,013.00",Integrated Speech and LanguageTherapy.,"80,100,000.00","80100000,80110000",NEGOTIATED_WITHOUT_PUBLICATION,EU_body_b61abb8d47a94bbdbf55dd49c80dda224e2c5d...,Halton Borough Council,...,"231,759.00",EUR,100.00,0.00,100.00,nan,0.00,0.00,100.00,widnes
296559,37628,f800c1a2-1e7f-4b8c-ab98-5eca494ef4ea,UK,"2,013.00",Reservoir Cleaning and Minor Repairs.,"65,100,000.00","65100000,90913200,50514200,90913000,90913100",NEGOTIATED_WITH_PUBLICATION,EU_body_4d093bb5e683694dc6736ae155321038c23417...,Severn Trent Water Limited,...,"5,119,766.00",EUR,100.00,0.00,100.00,nan,0.00,100.00,nan,coventry
296560,37629,f800c1a2-1e7f-4b8c-ab98-5eca494ef4ea,UK,"2,013.00",Reservoir Cleaning and Minor Repairs.,"65,100,000.00","65100000,90913200,50514200,90913000,90913100",NEGOTIATED_WITH_PUBLICATION,EU_body_4d093bb5e683694dc6736ae155321038c23417...,Severn Trent Water Limited,...,"5,119,766.00",EUR,100.00,0.00,100.00,nan,0.00,100.00,nan,coventry
296590,37660,f685d725-429e-4758-89b1-b8be327638af,UK,"2,013.00",Insurance Services Review 2013.,"66,510,000.00",66510000,NEGOTIATED,EU_body_e1bee1658002c6a174cd3346d29b1e2e35a453...,Yarlington Housing Group,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,yeovil
296593,37663,ebee9f07-3809-40ac-9bcc-d08858285e62,UK,"2,013.00",Insurance Services Review 2013.,"66,510,000.00",66510000,NEGOTIATED,EU_body_2a04a6e40d4e22a04565edc78334785466b220...,Aldwyck Housing Group,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,houghton regis
296594,37664,ef400254-aa00-4a47-8ae2-9ca0473fe4b7,UK,"2,013.00",Pre placement agreement for the provision of a...,"85,144,100.00",85144100,NEGOTIATED_WITHOUT_PUBLICATION,EU_body_049a72f50999a69ff4154df3620e5cb7da03a9...,Cheshire East Borough Council,...,"357,411.00",EUR,100.00,0.00,100.00,nan,0.00,0.00,100.00,macclesfield
296595,37665,f2c4e9da-bb64-42ac-ae8a-6ddd3a67ccf1,UK,"2,013.00",Tender for Insurance Contract.,"66,510,000.00","66510000,66518300,66515200,66515100,66515000,6...",NEGOTIATED,EU_body_34deb2be14b7962548bef15fa15f11129e51ee...,Humberside Fire and Rescue (HFRS) and HFR Solu...,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,hessle
296596,37666,f2c4e9da-bb64-42ac-ae8a-6ddd3a67ccf1,UK,"2,013.00",Tender for Insurance Contract.,"66,510,000.00","66510000,66518300,66515200,66515100,66515000,6...",NEGOTIATED,EU_body_34deb2be14b7962548bef15fa15f11129e51ee...,Humberside Fire and Rescue (HFRS) and HFR Solu...,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,hessle
296597,37667,f2c4e9da-bb64-42ac-ae8a-6ddd3a67ccf1,UK,"2,013.00",Tender for Insurance Contract.,"66,510,000.00","66510000,66518300,66515200,66515100,66515000,6...",NEGOTIATED,EU_body_34deb2be14b7962548bef15fa15f11129e51ee...,Humberside Fire and Rescue (HFRS) and HFR Solu...,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,hessle
296598,37668,f2c4e9da-bb64-42ac-ae8a-6ddd3a67ccf1,UK,"2,013.00",Tender for Insurance Contract.,"66,510,000.00","66510000,66518300,66515200,66515100,66515000,6...",NEGOTIATED,EU_body_34deb2be14b7962548bef15fa15f11129e51ee...,Humberside Fire and Rescue (HFRS) and HFR Solu...,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,hessle
296599,37669,f2c4e9da-bb64-42ac-ae8a-6ddd3a67ccf1,UK,"2,013.00",Tender for Insurance Contract.,"66,510,000.00","66510000,66518300,66515200,66515100,66515000,6...",NEGOTIATED,EU_body_34deb2be14b7962548bef15fa15f11129e51ee...,Humberside Fire and Rescue (HFRS) and HFR Solu...,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,hessle
296600,37670,f2c4e9da-bb64-42ac-ae8a-6ddd3a67ccf1,UK,"2,013.00",Tender for Insurance Contract.,"66,510,000.00","66510000,66518300,66515200,66515100,66515000,6...",NEGOTIATED,EU_body_34deb2be14b7962548bef15fa15f11129e51ee...,Humberside Fire and Rescue (HFRS) and HFR Solu...,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,hessle
296601,37671,f2c4e9da-bb64-42ac-ae8a-6ddd3a67ccf1,UK,"2,013.00",Tender for Insurance Contract.,"66,510,000.00","66510000,66518300,66515200,66515100,66515000,6...",NEGOTIATED,EU_body_34deb2be14b7962548bef15fa15f11129e51ee...,Humberside Fire and Rescue (HFRS) and HFR Solu...,...,nan,NaN,0.00,100.00,100.00,nan,100.00,100.00,100.00,hessle
296822,37901,fcf68676-3443-4f76-8658-fbb681125f64,UK,"2,013.00",Provision of Telecommunications DC Battery & C...,"32,000,000.00",32000000,NEGOTIATED_WITH_PUBLICATION,EU_body_118207546f464b5678188a280e23d882f331e0...,Northern Powergrid Limited,...,nan,NaN,100.00,0.00,100.00,nan,0.00,100.00,100.00,new penshaw
296855,37934,fe0df22c-c02b-42b1-bed9-7ca406fd1fa4,UK,"2,013.00",Supply of Amphotericin (Ambisome).,"33,600,000.00",33600000,NEGOTIATED_WITHOUT_PUBLICATION,EU_body_ede4014a3b596f870dd924039b18bf3451f163...,The Common Services Agency (more commonly know...,...,"10,444,601.00",EUR,100.00,0.00,100.00,nan,0.00,0.00,100.00,larkhall

In [82]:
sum_final_by_city = (
df[["buyer_city_clean","tender_finalPrice_EUR"]]
    .groupby(
        "buyer_city_clean")
    .sum()
    .sort_values("tender_finalPrice_EUR", ascending=False)
)
sum_final_by_city.head()

                  tender_finalPrice_EUR
buyer_city_clean
liverpool            857,807,242,092.00
london               352,143,913,411.04
manchester           272,769,338,154.00
rotherham            220,520,568,415.00
edinburgh            210,499,626,513.80

In [83]:
sum_final_by_city.to_csv('sum_final_by_city.csv')

In [85]:
df.head()

,Unnamed: 0,tender_id,tender_country,tender_year,tender_title,tender_mainCpv,tender_cpvs,tender_procedureType,buyer_id,buyer_name,...,tender_finalPrice_EUR,tender_finalPrice_currency,tender_indicator_INTEGRITY_ADVERTISEMENT_PERIOD,tender_indicator_INTEGRITY_CALL_FOR_TENDER_PUBLICATION,tender_indicator_INTEGRITY_DECISION_PERIOD,tender_indicator_INTEGRITY_NEW_COMPANY,tender_indicator_INTEGRITY_PROCEDURE_TYPE,tender_indicator_INTEGRITY_SINGLE_BID,tender_indicator_INTEGRITY_TAX_HAVEN,buyer_city_clean
0,3,0d7b8078-b007-48ae-aa7d-6c2a52056108,UK,nan,Older People — Creigiau and St Fagans.,"85,312,000.00",85312000,OPEN,EU_body_81cdafe504d6cc4a1ba541281e6c17178db683...,Cardiff City Council,...,nan,NaN,100.00,0.00,100.00,100.00,100.00,100.00,100.00,cardiff
1,63,09f1310f-8612-4313-8792-d003ad91b1f0,UK,nan,Mini-cabs and Taxis Saloons.,"60,000,000.00",60000000,OPEN,EU_body_c04712a23e83f993d38e793f12641216f9ae04...,London Borough of Haringey,...,nan,NaN,100.00,0.00,100.00,100.00,100.00,100.00,100.00,london
2,64,09f58d40-0790-4456-843e-dff2de5a2c77,UK,nan,4503 - AV installation - 32 teaching rooms,"32,322,000.00",32322000,RESTRICTED,EU_body_2ed4c44bc08e032ca54a8d626740fccf081f30...,University of Portsmouth,...,"155,478.00",EUR,100.00,0.00,100.00,nan,100.00,100.00,100.00,portsmouth
3,79,0e3caf26-6731-4a6b-84c6-046ff5528e98,UK,nan,Library resources.,"22,113,000.00","22113000,22200000,48161000",OPEN,EU_body_dd617693ccd2769369e8d5de79480636f119b4...,Crescent Purchasing Consortium,...,nan,NaN,0.00,100.00,nan,nan,100.00,nan,nan,salford
4,80,0e3caf26-6731-4a6b-84c6-046ff5528e98,UK,nan,Library resources.,"22,113,000.00","22113000,22200000,48161000",OPEN,EU_body_dd617693ccd2769369e8d5de79480636f119b4...,Crescent Purchasing Consortium,...,nan,NaN,0.00,100.00,nan,nan,100.00,nan,nan,salford